apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fusion-app
  template:
    metadata:
      labels:
        name: fusion-app
    spec:
      serviceAccountName: fusion-app
      containers:
        - name: fusion-app
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - fusion-app
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "fusion-app"
