// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.AppEvent":                schema_pkg_apis_fusionapp_v1alpha1_AppEvent(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.AppEventSpec":            schema_pkg_apis_fusionapp_v1alpha1_AppEventSpec(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.AppEventStatus":          schema_pkg_apis_fusionapp_v1alpha1_AppEventStatus(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.EdgeResource":            schema_pkg_apis_fusionapp_v1alpha1_EdgeResource(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.EdgeResourceSpec":        schema_pkg_apis_fusionapp_v1alpha1_EdgeResourceSpec(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.EdgeResourceStatus":      schema_pkg_apis_fusionapp_v1alpha1_EdgeResourceStatus(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionApp":               schema_pkg_apis_fusionapp_v1alpha1_FusionApp(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppInstance":       schema_pkg_apis_fusionapp_v1alpha1_FusionAppInstance(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppInstanceSpec":   schema_pkg_apis_fusionapp_v1alpha1_FusionAppInstanceSpec(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppInstanceStatus": schema_pkg_apis_fusionapp_v1alpha1_FusionAppInstanceStatus(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppSpec":           schema_pkg_apis_fusionapp_v1alpha1_FusionAppSpec(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppStatus":         schema_pkg_apis_fusionapp_v1alpha1_FusionAppStatus(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.HumanResource":           schema_pkg_apis_fusionapp_v1alpha1_HumanResource(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.HumanResourceSpec":       schema_pkg_apis_fusionapp_v1alpha1_HumanResourceSpec(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.HumanResourceStatus":     schema_pkg_apis_fusionapp_v1alpha1_HumanResourceStatus(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEvent":           schema_pkg_apis_fusionapp_v1alpha1_ResourceEvent(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventBus":        schema_pkg_apis_fusionapp_v1alpha1_ResourceEventBus(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventBusSpec":    schema_pkg_apis_fusionapp_v1alpha1_ResourceEventBusSpec(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventBusStatus":  schema_pkg_apis_fusionapp_v1alpha1_ResourceEventBusStatus(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventSpec":       schema_pkg_apis_fusionapp_v1alpha1_ResourceEventSpec(ref),
		"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventStatus":     schema_pkg_apis_fusionapp_v1alpha1_ResourceEventStatus(ref),
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_AppEvent(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AppEvent is the Schema for the appevents API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.AppEventSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.AppEventStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.AppEventSpec", "github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.AppEventStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_AppEventSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AppEventSpec defines the desired state of AppEvent",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_AppEventStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AppEventStatus defines the observed state of AppEvent",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_EdgeResource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EdgeResource is the Schema for the edgeresources API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.EdgeResourceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.EdgeResourceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.EdgeResourceSpec", "github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.EdgeResourceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_EdgeResourceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EdgeResourceSpec defines the desired state of EdgeResource",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_EdgeResourceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "EdgeResourceStatus defines the observed state of EdgeResource",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_FusionApp(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FusionApp is the Schema for the fusionapps API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppSpec", "github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_FusionAppInstance(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FusionAppInstance is the Schema for the fusionappinstances API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppInstanceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppInstanceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppInstanceSpec", "github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.FusionAppInstanceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_FusionAppInstanceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FusionAppInstanceSpec defines the desired state of FusionAppInstance",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_FusionAppInstanceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FusionAppInstanceStatus defines the observed state of FusionAppInstance",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_FusionAppSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FusionAppSpec defines the desired state of FusionApp",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_FusionAppStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FusionAppStatus defines the observed state of FusionApp",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_HumanResource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HumanResource is the Schema for the humanresources API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.HumanResourceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.HumanResourceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.HumanResourceSpec", "github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.HumanResourceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_HumanResourceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HumanResourceSpec defines the desired state of HumanResource",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_HumanResourceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HumanResourceStatus defines the observed state of HumanResource",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceEvent(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceEvent is the Schema for the resourceevents API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventSpec", "github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceEventBus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceEventBus is the Schema for the resourceeventbuses API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventBusSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventBusStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventBusSpec", "github.com/lxs137/fusion-app/pkg/apis/fusionapp/v1alpha1.ResourceEventBusStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceEventBusSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceEventBusSpec defines the desired state of ResourceEventBus",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceEventBusStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceEventBusStatus defines the observed state of ResourceEventBus",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceEventSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceEventSpec defines the desired state of ResourceEvent",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_fusionapp_v1alpha1_ResourceEventStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ResourceEventStatus defines the observed state of ResourceEvent",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
